[msbuild]
project = "../test-api.sln"
configuration = "Release"
[github]
user = "diversiwaver"
repo = "test-repo"
[test]
enable = false
[coverage]
enable = false
[nuget]
publish = true
source = "https://nuget.pkg.github.com/diversiwaver/index.json"