[msbuild]
project = "../test-api.sln"
[github]
user = "diversiwaver"
repo = "test-repo"
version_prefix = "v"
[nuget]
publish = false
[changelog]
publish = false

[[pack]]
publish = false
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]

[[pack]]
publish = false
rid = ["rhel-x64"]
kinds = ["rpm", "tar"]

[[pack]]
publish = false
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]