[msbuild]
project = "../test-api/WebApi.DTOs/WebAPI.DTO.csproj"
configuration = "Release"
[github]
user = "diversiwaver"
repo = "test-repo"

[coverage]
enable = false
[nuget]
publish = true
source = "https://nuget.pkg.github.com/diversiwaver/index.json"
